<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="192.168.1.4" ignored="0" name="Test" tests="3" failures="1" timestamp="2020-03-30T00:55:07 IST" time="43.422" errors="0">
  <testcase name="shouldAnswerWithTrue" time="0.011" classname="jenkins.selenium_testng_jenkins.AppTest"/>
  <testcase name="login" time="28.782" classname="urllogin.Login"/>
  <testcase name="loginfail" time="10.987" classname="urllogin.Login">
    <failure type="java.lang.AssertionError" message="expected [Home | Let&amp;apos;s Kode It] but found [Let&amp;apos;s Kode It]">
      <![CDATA[java.lang.AssertionError: expected [Home | Let's Kode It] but found [Let's Kode It]
at urllogin.Login.loginfail(Login.java:41)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginfail -->
</testsuite> <!-- Test -->
